### ISSUE TITLE
Review and Rating collection

### ISSUE THREAD

**Issue by cdrafael** [look-n-cook/Look-n-Cook#39]
“Do all work for this task in a branch called issue-XX”, where “XX” is the issue number.

## What needs to be accomplished:
Create a way for a user to give a recipe a 1-5 rating and say something about the recipe.
This is similar to notes from the in-class digits project.
Include:
<ul>
    <li>Poster's name</li>
    <li>Date posted</li>
    <li>Rating</li>
    <li>Comment</li>
</ul>

**Comment by jsome635** [comment]
Merged to master.

**Comment by jsome635** [comment]
BUG: anyone using the app can delete any comment from a recipe.
